### ISSUE TITLE
想知道作者是怎么解决recyclerview 下边的这个bug的

### ISSUE THREAD

**Issue by tianshaokai** [plusend/DiyCode#4]
1. RecyclerView Bug：IndexOutOfBoundsException: Inconsistency detected. Invalid item position

**Comment by plusend** [comment]
这 bug 什么场景下出现呢？我没有遇到过啊。
我这的 recyclerview 主要是用 [MultiType](https://github.com/drakeet/MultiType) 进行加载的。

**Comment by tianshaokai** [comment]
下拉刷新的时候 ，向上滑动recyclerview就出现了，你说的这个库我知道，可是好多东西不太懂，看不懂你插入数据的地方

**Comment by plusend** [comment]
我这没加下拉刷新呢。
插入数据的地方，我看了下。就是用的 adapter 的 notifyItemInserted 、notifyItemChanged 等几个标准 API 方法。另外对返回的数据个数做了判断：小于 20 个的话就表示没有更多的数据需要加载了，此时就更新下 FooterView。
