### ISSUE TITLE
编译出错 Dex cannot parse version 52 byte code

### ISSUE THREAD

**Issue by dasenlin2013** [plusend/DiyCode#5]
Error:Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.

我用的是24.0.2的sdk，support包是24.2.1的，是不是不兼容？

**Comment by plusend** [comment]
看起来是跟 JAVA 版本有关系，我 Google 了下，好多类似的情况但是没找到确切的答案。所以还是得靠你自己喽！
buildTools 和 library 的版本，我一般都用最新的。

**Comment by dasenlin2013** [comment]
好的，谢谢

**Comment by plusend** [comment]
更新了 Android Studio 2.3 之后，使用最新的 Gradle 2.3.0 构建报了这个问题，Google 了之后没有解决。
目前的处理是使用了 Android Studio 2.3，但是依然使用的 Gradle 2.2.3 版本。

**Comment by gongzelong0718** [comment]
请问问题如何解决的呢？

> 我用的是24.0.2的sdk，support包是24.2.1的

您说的support包是怎么看的呢？不是build.gradle里规定的吗？

```
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support:preference-v7:25.3.1'
    compile 'com.android.support:design:25.3.1'
```

sdk我本地有很多个（SDK Manager里面），如而确定目前用的是哪个呢？

**Comment by gongzelong0718** [comment]
您说的24.0.2的sdk，应该就是compileSdkVersion的吧

compileSdkVersion 25
